name: Run Python script
on:
  schedule:
    - cron: '0 2,8,14,20 * * *'  # This schedules the action to run at 2, 8, 14, and 20 UTC.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2

      - name: Install dependencies
        run: |
          conda env create -f environment.yml
        shell: bash -l {0}

      - name: Run script
        run: |
          conda activate myenv
          python download_hrrr.py
        shell: bash -l {0}

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update data" -a
          git push