name: Run Python script

on:
  schedule:
    - cron:  '0 0 * * *'  # This schedules the action to run once a day at midnight.

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.x

    - name: Install dependencies
      run: |
        conda env create -f environment.yml
      shell: bash -l {0}

    - name: Run script
      run: |
        conda activate myenv
        python download_hrrr.py
      shell: bash -l {0}

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update data" -a
        git push